[project]
name = "football-data-scout"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "curl-cffi>=0.15.0",
    "mplsoccer>=1.6.1",
    "numpy>=2.4.4",
    "pandas>=3.0.2",
    "streamlit>=1.57.0",
]

[dependency-groups]
dev = [
    "ipykernel>=7.2.0",
]
